name: Front End Assets Linter
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  lint-assets:
    name: Stylelint & ESlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files_yaml: |
            styles:
              - '**/*.scss'
            scripts:
              - '**/*.js'
      - name: Set up Node
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up NPM auth
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_TOKEN }}
          npm config set @humanoidfr:registry http://npm.pkg.github.com/
      - name: Install npm packages
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: bash
        run: npm ci stylelint eslint
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run Stylelint
        if: steps.changed-files.outputs.styles_any_changed == 'true'
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: false
          stylelint_input: '**/*.scss'
          stylelint_config: './.stylelintrc'
      - name: Run ESlint
        if: steps.changed-files.outputs.scripts_any_changed == 'true'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: false
